import { COMPANIES } from "../../field-spec";
import type { OnboardDefinition } from "../types";

/** Service-owned onboarding contract. Generic code validates and executes it. */
export const lightningOnboarding: OnboardDefinition = {
    service: "lightning",
    codePattern: /^[A-Z0-9][A-Z0-9-]{0,47}$/,
    codeHelp: "Uppercase letters, digits and hyphens only — the column CHECK rejects lowercase and underscores.",
    label: "＋ Add project",
    title: "Add a new Lightning project",
    description:
      "Creates one disabled row in lightning.lightning_project_configs. The two ring radii are client-approved and have no defaults.",
    outsideHalo: [
      "The red and amber radii are a client-approved safety decision, not a default — the repo's own wizard refuses to proceed without both. Confirm them before enabling.",
      "Remember that an uncertainty margin WIDENS the trigger ring, and site extent does too: the ring is measured from the site boundary. Both default to 0 here and can be set in the editor.",
    ],
    fields: [
      {
        column: "project_code",
        label: "Project code",
        kind: "text",
        required: true,
        notNull: true,
        help: "Uppercase only — anything else is refused.",
      },
      {
        column: "company",
        label: "Company",
        kind: "select",
        required: false,
        notNull: false,
        // Identity only — nothing reads it — but it drives the card watermark and
        // the search box, so it is worth setting while someone knows the answer.
        // Blank stays legal: a new operating company arrives before this list does.
        options: ["", ...COMPANIES],
        help: "Identity only; no code reads it. Sets the card's background mark and makes the project findable by company.",
      },
      {
        column: "latitude",
        label: "Latitude",
        kind: "number",
        required: true,
        notNull: true,
        range: { min: 1.1, max: 1.5 },
        help: "Singapore only. Use the address lookup if you do not have coordinates.",
      },
      {
        column: "longitude",
        label: "Longitude",
        kind: "number",
        required: true,
        notNull: true,
        range: { min: 103.55, max: 104.15 },
      },
      {
        column: "site_address",
        label: "Site address",
        kind: "text",
        required: false,
        notNull: false,
        help: "Optional. Filled in by the address lookup.",
      },
      {
        column: "red_radius_m",
        label: "Red radius (m)",
        kind: "number",
        required: true,
        notNull: true,
        range: { min: 1, max: 100000 },
        help: "Stop-work ring. Client-approved — there is deliberately no default.",
      },
      {
        column: "amber_radius_m",
        label: "Amber radius (m)",
        kind: "number",
        required: true,
        notNull: true,
        range: { min: 1, max: 100000 },
        help: "Warning ring. Usually wider than red; a narrower one is allowed but warns.",
      },
      {
        column: "site_extent_radius_m",
        label: "Site extent (m)",
        kind: "number",
        hidden: true,
        required: false,
        notNull: true,
        fallback: "0",
        range: { min: 0, max: 50000 },
        help: "Rings are measured from the site boundary, so this widens both. Written as 0; set it in the editor for a site whose extent matters.",
      },
      {
        column: "red_detection_types",
        label: "🔴 Red strike types",
        kind: "multi",
        required: false,
        notNull: true,
        fallback: "G",
        options: ["G", "C"],
        help: "G = cloud-to-ground, C = intra-cloud. Ground-only by default; adding C makes a stop fire on cloud-to-cloud activity too.",
      },
      {
        column: "amber_detection_types",
        label: "🟠 Amber strike types",
        kind: "multi",
        required: false,
        notNull: true,
        // The column's own default is {C,G}. Prefilled as G here so a new project
        // starts on ground strikes for both tiers and widening is a decision
        // someone makes rather than inherits.
        fallback: "G",
        options: ["G", "C"],
        help: "Ground-only to start with, matching red. Widen it here or in the editor once the site wants cloud activity to raise a watch.",
      },
      {
        column: "feed_stale_after_seconds",
        label: "Feed stale after (s)",
        kind: "number",
        // Hidden but still written: the live column default is 360 while
        // setup.sql says 600, so leaving it out would quietly onboard a project
        // onto a six-minute staleness window nobody chose.
        hidden: true,
        required: false,
        notNull: true,
        fallback: "600",
        range: { min: 60, max: 86400 },
        help: "Ten minutes. Past this the feed counts as stale and the state goes DEGRADED — which never downgrades an open STOP.",
      },
      {
        column: "amber_enabled",
        label: "Amber alerts",
        kind: "toggle",
        required: false,
        notNull: true,
        fallback: "true",
        help: "Off is not a mute: amber detections are not evaluated at all, and a stop then clears straight to SAFE with no intermediate WATCH.",
      },
      {
        column: "red_dwell_seconds",
        label: "🔴 Red dwell (s)",
        kind: "number",
        hidden: true,
        required: false,
        notNull: true,
        fallback: "1200",
        range: { min: 1, max: 86400 },
        help: "How long the stop persists after the last qualifying detection. Twenty minutes by default.",
      },
      {
        column: "amber_dwell_seconds",
        label: "🟠 Amber dwell (s)",
        kind: "number",
        hidden: true,
        required: false,
        notNull: true,
        fallback: "1200",
        range: { min: 1, max: 86400 },
        help: "Also the amber debounce: a new amber waits at least this long after the last one, so a storm edge crossing the ring does not ping-pong.",
      },
      {
        column: "working_hours_start_hhmm",
        label: "Working hours start",
        kind: "hhmm",
        hidden: true,
        required: false,
        notNull: false,
        fallback: "0800",
        help: "HHMM, e.g. 0800. Both ends or neither.",
      },
      {
        column: "working_hours_end_hhmm",
        label: "Working hours end",
        kind: "hhmm",
        hidden: true,
        required: false,
        notNull: false,
        fallback: "1900",
      },
      {
        column: "remove_sunday_notifications",
        label: "Mute Sundays",
        kind: "toggle",
        hidden: true,
        required: false,
        notNull: true,
        fallback: "true",
        help: "Outbound only, and it never mutes the green that closes an open stop — nobody is left under a communicated stop-work instruction by a calendar setting. On by default for a new project.",
      },
      {
        column: "remove_ph_notifications",
        label: "Mute public holidays",
        kind: "toggle",
        hidden: true,
        required: false,
        notNull: true,
        fallback: "true",
        help: "Same, for the hard-coded holiday list, which runs out at the end of 2027.",
      },
      {
        column: "whatsapp_group_id",
        label: "WhatsApp group ID",
        kind: "groups",
        required: false,
        notNull: false,
      },
      {
        column: "instance_name",
        label: "WhatsApp instance",
        kind: "text",
        required: false,
        notNull: false,
      },
      {
        column: "client_id",
        label: "Client ID",
        kind: "text",
        required: false,
        notNull: false,
      },
      {
        column: "lambda_url",
        label: "Send-message URL",
        kind: "text",
        required: false,
        notNull: false,
        envDefault: "DEFAULT_LAMBDA_URL_SEND",
      },
    ],
  };
